default:
  image: ubuntu:latest

stages:
- build
- test
- deploy

markdown_lint:
  stage: test
  image: ruby:latest
  #rules:
  #  - if: '$CI_COMMIT_MODIFIED_FILES =~ /\.md$/'
  script:
    - gem install mdl
    - mdl $(find . -type f -name "*.md")

markdown_link:
  stage: test
  image: node:latest
  script:
    - npm install -g markdown-link-check
    - echo '{}' > /tmp/config.json
    - markdown-link-check -c /tmp/config.json $(find . -type f -name "*.md")

spelling:
  stage: test
  image: node:latest
  script:
    - npm install -g cspell@latest
    - cspell --color --locale "en,fr" --config .ci/cpsell/config.json "README.md reports/** tutorials/**"
