default:
  image: ubuntu:latest

stages:
- build
- test
- deploy

include:
  - template: Code-Quality.gitlab-ci.yml
  - template: Security/SAST.gitlab-ci.yml
  - template: Security/Secret-Detection.gitlab-ci.yml
  - template: Security/Dependency-Scanning.gitlab-ci.yml
  - template: Security/Container-Scanning.gitlab-ci.yml
  - template: Security/License-Scanning.gitlab-ci.yml

variables:
  PYTHONPATH: "$CI_PROJECT_DIR/src"
  SECRET_DETECTION_EXCLUDED_PATHS: "tst"

markdown_lint:
  stage: test
  image: node:latest
  #rules:
  #  - if: '$CI_COMMIT_MODIFIED_FILES =~ /\.md$/'
  script:
    - npm install -g markdownlint-cli
    - markdownlint -c .markdownlint.json $(find . -type f -name "*.md")

markdown_link:
  stage: test
  image: node:latest
  script:
    - npm install -g markdown-link-check
    - echo '{}' > /tmp/config.json
    - markdown-link-check -c /tmp/config.json $(find . -type f -name "*.md" -not -path ".git*")

spelling:
  stage: test
  image: node:latest
  script:
    - npm install -g cspell@latest
    - cspell --color --locale "en,fr" --config .ci/cpsell/config.json README.md tutorials/** reports/**

unit-test-job:
  image: python:latest
  stage: test
  script:
    - echo "Running unit tests..."
    - python3 -m pip install pytest
    - python3 -m pip install -r requirements.txt
    - python3 -m pytest tst --junitxml=unit_test_results.xml
  artifacts:
    reports:
      junit: unit_test_results.xml
    when: always
    expire_in: 1 days

lint-test-job:
  image: python:latest
  stage: test
  script:
    - echo "Runing pylint tests"
    - python3 -m pip install pylint mypy
    - python3 -m pylint src/**
    - echo "Runing mypy tests"
    - for file in $(find src -type f -name "*.py"); do python3 -m mypy $file; done

bandit-test-job:
  image: python:latest
  stage: test
  script:
    - python3 -m pip install --upgrade pip
    - python3 -m pip install --upgrade setuptools
    - python3 -m pip install bandit
