default:
  image: ubuntu:latest

stages:
- build
- test
- deploy

markdownlint:
  stage: test
  image: ruby:latest
  script:
    - gem install mdl
    - mdl $(find . -type f -name "*.md")

spelling:
  stage: test
  image: node:latest
  script:
    - npm install -g cspell@latest
    - cspell --color --locale "en" --config .ci/cpsell config.json "**"
