default:
  image: ubuntu:latest

stages:
- build
- test
- deploy

sast:
  stage: test
  script:
    - apt-get update && apt-get install -y ruby
    - gem install mdl
    - mdl $(find . -type f -name "*.md")
